### ISSUE TITLE
Feedback on markdown-doctest

### ISSUE THREAD

**Issue by Widdershin** [arlac77/pratt-parser#28]
Hello!

I see that you're using markdown-doctest! Great 😺 

I was just reaching out to ask if you have any feedback around how it was to set up/use markdown-doctest.

Did you run into any pain points? Was anything particularly awesome?

(Please feel free to just close this issue if you don't have time to respond.)

**Comment by arlac77** [comment]
markdowns-docket works perfect.
only one improvement:

Maybe the following content could be the default for _.markdown-doctest-setup.js_
```js
module.exports = {
  require: {
    '<<npm-package-name>>': require(<<main from package.json>>)
  }
}
```
